name = "PowerModelsITD"
uuid = "615c3f80-b0cb-4ecd-88fe-27bee056c380"
authors = ["Juan Ospina", "David M Fobes"]
repo = "https://github.com/lanl-ansi/PowerModelsITD.jl.git"
version = "0.7.1"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"

[compat]
InfrastructureModels = "0.7.3"
Ipopt = "0.9, 1.0.2"
JSON = "~0.18, ~0.19, ~0.20, ~0.21"
JuMP = "~0.22, ~0.23, 1"
PowerModels = "0.19.4"
PowerModelsDistribution = "0.14.2"
SCS = "~1.0, ~1.1"
julia = "1.6"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "SCS", "Test"]
